const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    AUTHENTICATION_ERROR: 4,
    AUTHORIZATION_ERROR: 5,
    RESOURCE_NOT_FOUND: 6
};

export default EErrors;